Make server act as "aggregator"
ZcashFoundation/frost-zcash-demo pull request #265
Opened 2024-07-18 21:40 UTC by conradoplg

Closes #251 

Basically:

- This moves the SessionState from the Server to the Coordinator, with some modifications
- This removes most functions from the state, adding a new `send` and `receive` instead

I ended up doing some refactorings to make the implementation simpler. I should've split that into another PR, sorry!

- I added a ProcessedArgs struct to the Coordinator which is created from a Args, and does all the handling related to reading inputs files or stdin, etc.

2024-08-08 22:12 UTC, natalieesk commented on coordinator/src/comms/http.rs
> +/// This can be used by a Coordinator to help maitain state and handle
* maintain

2024-08-08 22:29 UTC, natalieesk requested changes
Just a little typo, otherwise all great

2024-08-08 22:55 UTC, conradoplg commented on coordinator/src/comms/http.rs
> +/// This can be used by a Coordinator to help maitain state and handle
```suggestion
/// This can be used by a Coordinator to help maintain state and handle
```

2024-08-09 08:55 UTC, mpguerra approved these changes

2024-08-14 21:53 UTC, merged