Improve consistency of testing across projects
ZcashFoundation/frost-zcash-demo pull request #76
Opened 2023-09-11 14:54 UTC by natalieesk

This closes #37 

I've added a separate project solely for an integration test across all the other projects. this has just been done for trusted dealer. If we think it's useful we can add one for the DKG journey as well

2023-09-12 18:27 UTC, conradoplg requested changes
Looks good, I committed a suggestion in dc0f6a9, see comment. There is just some leftover code to cleanup.

2023-09-12 18:59 UTC, conradoplg commented on tests/tests/integration_tests.rs
> +    assert_eq!(1, 1)
I see you fixed in the next PR, feel free to ignore this

2023-09-18 12:41 UTC, natalieesk commented on participant/src/main.rs
> +// }
We can delete

2023-09-27 16:26 UTC, conradoplg approved these changes

2023-09-27 16:27 UTC, merged